### ISSUE TITLE
Error in rule antismash

### ISSUE THREAD

**Issue by 4br4ha4mRR** [Carrion-lab/bacLIFE#15]
Hi,
I'm running 45 genomes through bacLIFE but keep getting this error, and te pipeline crashes:

Activating conda environment: antismash_bacLIFE
Traceback (most recent call last):
  File "/home/rot3cksxot3/miniconda3/envs/antismash_bacLIFE/bin/antismash", line 10, in <module>
    sys.exit(entrypoint())
  File "/home/rot3cksxot3/miniconda3/envs/antismash_bacLIFE/lib/python3.10/site-packages/antismash/__main__.py", line 121, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/home/rot3cksxot3/miniconda3/envs/antismash_bacLIFE/lib/python3.10/site-packages/antismash/__main__.py", line 111, in main
    return antismash.run_antismash(sequence, options)
  File "/home/rot3cksxot3/miniconda3/envs/antismash_bacLIFE/lib/python3.10/site-packages/antismash/main.py", line 688, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/home/rot3cksxot3/miniconda3/envs/antismash_bacLIFE/lib/python3.10/site-packages/antismash/main.py", line 755, in _run_antismash
    analysis_timings = analyse_record(record, options, get_analysis_modules(), module_results)
  File "/home/rot3cksxot3/miniconda3/envs/antismash_bacLIFE/lib/python3.10/site-packages/antismash/main.py", line 303, in analyse_record
    run_module(record, module, options, previous_result, timings)
  File "/home/rot3cksxot3/miniconda3/envs/antismash_bacLIFE/lib/python3.10/site-packages/antismash/main.py", line 275, in run_module
    results = module.run_on_record(record, results, options)
  File "/home/rot3cksxot3/miniconda3/envs/antismash_bacLIFE/lib/python3.10/site-packages/antismash/modules/clusterblast/__init__.py", line 153, in run_on_record
    results.general = perform_clusterblast(options, record, clusters, proteins)
  File "/home/rot3cksxot3/miniconda3/envs/antismash_bacLIFE/lib/python3.10/site-packages/antismash/modules/clusterblast/clusterblast.py", line 41, in perform_clusterblast
    blastoutput = run_diamond_on_all_regions(regions, database)
  File "/home/rot3cksxot3/miniconda3/envs/antismash_bacLIFE/lib/python3.10/site-packages/antismash/modules/clusterblast/core.py", line 85, in run_diamond_on_all_regions
    stdout = subprocessing.run_diamond_search(temp_file.name, database, mode="blastp", opts=extra_args)
  File "/home/rot3cksxot3/miniconda3/envs/antismash_bacLIFE/lib/python3.10/site-packages/antismash/common/subprocessing/diamond.py", line 84, in run_diamond_search
    return run_diamond(mode, args).stdout
  File "/home/rot3cksxot3/miniconda3/envs/antismash_bacLIFE/lib/python3.10/site-packages/antismash/common/subprocessing/diamond.py", line 57, in run_diamond
    return run(params)
  File "/home/rot3cksxot3/miniconda3/envs/antismash_bacLIFE/lib/python3.10/site-packages/antismash/common/subprocessing/diamond.py", line 41, in run
    raise RuntimeError(message)
RuntimeError: diamond failed to run: blastp
[Sun Aug  4 07:58:51 2024]
Error in rule antismash:
    jobid: 140
    input: intermediate_files/annot/arabica_X00005_O/Microvirga_arabica_X00005_O.gbk
    output: intermediate_files/antismash/Microvirga_arabica_X00005_O/Microvirga_arabica_X00005_O.gbk
    conda-env: antismash_bacLIFE
    shell:
        antismash --cb-general --cb-knownclusters --cb-subclusters --output-dir intermediate_files/antismash/Microvirga_arabica_X00005_O/ --asf --pfam2go --genefinding-tool prodigal --smcog-trees intermediate_files/annot/arabica_X00005_O/Microvirga_arabica_X00005_O.gbk
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Sun Aug  4 08:00:41 2024]
Finished job 104.
9 of 91 steps (10%) done
[Sun Aug  4 08:02:15 2024]
Finished job 136.
10 of 91 steps (11%) done
[Sun Aug  4 08:04:21 2024]
Finished job 110.
11 of 91 steps (12%) done
[Sun Aug  4 08:08:19 2024]
Finished job 103.
12 of 91 steps (13%) done
[Sun Aug  4 08:08:36 2024]
Finished job 128.
13 of 91 steps (14%) done
[Sun Aug  4 08:11:20 2024]
Finished job 121.
14 of 91 steps (15%) done
[Sun Aug  4 08:14:58 2024]
Finished job 106.
15 of 91 steps (16%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-08-04T074205.478234.snakemake.log
WorkflowError:
At least one job did not complete successfully.

 I have attached the log file for the error.
[2024-08-04T074205.478234.snakemake.log](https://github.com/user-attachments/files/16489139/2024-08-04T074205.478234.snakemake.log)

**Comment by gguerr001** [comment]
Could you tell us which version of antismash is installed in the conda environment `antismash_bacLIFE` and if in the folder `intermediate_files/antismash` is there any sucessfull folder with the full antismash output of any of the genomes.

**Comment by 4br4ha4mRR** [comment]
Thank you for your time 

I have Antismash v7.1.0 installed. Yes, I have folders with the full Antismash output of some of the genomes.
I was looking at some problems some users have had with the same output. I was able to contend with error by decreasing the number of cores (jobs). I was using snakemake -j 8 and was able to run using -j 4. 

Thanks for replying
